name: Code Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Gradle과 JaCoCo 플러그인을 사용하여 테스트를 실행하고 코드 커버리지 보고서를 생성합니다.
      - name: Run tests with JaCoCo
        run: ./gradlew test jacocoTestReport

      # 생성된 코드 커버리지 보고서를 GitHub Actions 아티팩트로 업로드합니다.
      - name: Upload code coverage report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: build/reports/jacoco/test/html

      # Checkstyle 검증
      - name: runner / checkstyle
        uses: dbelyaev/action-checkstyle@v0.7.4
        with:
          github_token: ${{ secrets.CHECKSTYLE_TOKEN }}
          reporter: github-pr-review
          checkstyle_config_path: ./config/rule-config/naver-checkstyle-rules.xml
          suppressions-file: ./config/rule-config/naver-checkstyle-suppressions.xml.xml
          level: warning
